name: Release

on:
  push:
    branches:
      - main

env:
  NAME: test-feature
  FEATURE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais/feature

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release chart
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # ratchet:azure/setup-helm@v5
        with:
          version: v3.20.2
      - id: version
        run: echo "version=0.0.${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"
      - run: |-
          sed -i "s/^version: .*/version: ${{ steps.version.outputs.version }}/g" charts/Chart.yaml
          helm package charts
      - id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # ratchet:google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: gh-${{ env.NAME }}@nais-io.iam.gserviceaccount.com
          token_format: access_token
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # ratchet:docker/login-action@v4
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - run: helm push ${{ env.NAME }}-${{ steps.version.outputs.version }}.tgz ${{ env.FEATURE_REPOSITORY }}

  deploy:
    name: Deploy
    needs: release
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@58a70a338b16dc646373c91724fc7e7522d085a4 # ratchet:nais/fasit-deploy@v4.0.1
        with:
          chart: ${{ env.FEATURE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.release.outputs.version }}
          targets: |
            [
              { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "tenant" } }
            ]
